---
version: '3.8'

volumes:
  mongo_data:
    driver: local
  node_modules:
    driver: local

networks:
  app-network:

services:
  app:
    build:
      context: .
    env_file: .env
    ports:
      - 127.0.0.1:5001:5000
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: on-failure

  mongodb:
    image: mongo:5-focal
    env_file: .env
    volumes:
      - mongo_data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    restart: on-failure
