---
services:
  mongoadmin:
    image: mongo-express:0.54.0
    restart: always
    depends_on: 
      - mongodb
    ports:
      - 8081:8081
    networks:
      - app-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
