module.exports.words = [
    "action citoyenne",
    "after'conf",
    "afterwork",
    "apéro",
    "atelier",
    "ateliers",
    "banquet",
    "beaujolais",
    "braderie",
    "bistrot",
    "brocante",
    "café actualité",
    "café littéraire",
    "café public",
    "camp nationaliste",
    "camp chouan",
    "camp d’été",
    "camp d’hiver",
    "camp de rentrée",
    "camp de printemps",
    "carrefour royal",
    "célébration",
    "cercle d’étude",
    "cercles d’études",
    "ciné-club",
    "cocktail de rentrée",
    "colloque",
    "concert",
    "conf",
    "conf.",
    "conférence",
    "conférence-cocktail",
    "conférence-débat",
    "conférence-dédicace",
    "conférence-dîner",
    "conférence-témoignage",
    "conférences",
    "congrès",
    "cortège",
    "débat avec",
    "dédicace",
    "dédicaces",
    "dédicacera",
    "déjeuner-débat",
    "demi-marathon",
    "déposer votre candidature",
    "dîner",
    "dîner-conférence",
    "dîner-spectacle",
    "échanger",
    "exposition",
    "fête de",
    "fête des",
    "fête du",
    "fête saint",
    "fête sainte",
    "formation",
    "forum de",
    "hommage à",
    "hommage au",
    "hommage des",
    "hommage :",
    "inauguration",
    "inscrivez-vous",
    "je participe",
    "grande journée",
    "grande réunion",
    "journée de synthèse nationale",
    "journée découverte",
    "journée d’amitié",
    "journées",
    "kermesse",
    "lancement",
    "manifestation contre",
    "manifestation pour",
    "manifestation du",
    "manifestation de",
    "marathon",
    "maraude",
    "marche pour",
    "marché de noël",
    "marché du livre",
    "master class",
    "masterclass",
    "messe à la",
    "messe votive",
    "messe pour",
    "messe de",
    "messe en mémoire",
    "messe solennelle",
    "neuvaine",
    "nuit royale",
    "oktoberfest",
    "obsèques",
    "pause musicale",
    "pauses musicales",
    "parcours",
    "passeurs d’hommes",
    "pèlerinage",
    "petit déjeuner",
    "petit-déjeuner",
    "petit-déjeuner-débat",
    "petit-déjeuner-conférence",
    "pique-nique",
    "pique nique",
    "porte ouverte",
    "portes ouvertes",
    "pot de",
    "pot d'",
    "présentation",
    "rencontre avec",
    "rencontres",
    "rencontrez-nous",
    "rencontrons-nous",
    "rentrée militante",
    "repas",
    "réunion-conférence",
    "réunion royaliste",
    "réunion patriote",
    "réunion nationaliste",
    "réunion d’information",
    "réunion du",
    "réunion de",
    "réunion des",
    "réunion-débat",
    "rosaire pour la france",
    "rosaire pour la vie",
    "saint-patrick",
    "salon du",
    "saluer",
    "stage",
    "séance",
    "semi-marathon",
    "séminaire",
    "session",
    "soirées",
    "soirée",
    "soirée-débat",
    "soirée/débat",
    "sortie culturelle",
    "son et lumière",
    "stand",
    "table ronde",
    "tombola",
    "tournoi",
    "tractage",
    "tracts",
    "université d’été",
    "veillée pour la vie",
    "vernissage",
    "verre",
    "vente de noël",
    "vide-greniers",
    "vide greniers",
    "vide-maison",
    "vide maison",
    "visite guidée",
    "week-end de formation",
    "weekend de formation",
    "weekend de la liberté",
    "aix :",
    "amiens",
    "bordeaux :",
    "clermont :",
    "grenoble :",
    "le mans :",
    "la rochelle :",
    "lyon :",
    "marseille :",
    "nantes :",
    "nancy :",
    "nice :",
    "perpignan :",
    "saumur :",
    "toulon :",
    "toulouse :",
    "Ile de France :",
    "ile de france :"
]
